# Generated by Django 3.2.9 on 2021-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211214_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidadDeEquipos', models.IntegerField()),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
    ]
