# Generated by Django 3.2.9 on 2021-12-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_arbitro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('continente', models.CharField(max_length=40)),
                ('tecnico', models.CharField(max_length=40)),
            ],
        ),
    ]
