# Generated by Django 3.2.9 on 2021-12-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_seleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitro',
            name='dirigeBien',
        ),
    ]
